#!/usr/bin/env python3
"""
AI Systems Manager - Setup Script
Helps users securely configure the environment
"""
import os
import getpass
import secrets
from pathlib import Path
import bcrypt

def generate_secure_keys():
    """Generate secure random keys"""
    return {
        'JWT_SECRET_KEY': secrets.token_urlsafe(32),
        'SESSION_SECRET_KEY': secrets.token_urlsafe(32),
        'DATABASE_ENCRYPTION_KEY': secrets.token_urlsafe(32)
    }

def hash_password(password: str) -> str:
    """Hash password using bcrypt"""
    return bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

def main():
    """Interactive setup"""
    print("🚀 AI Systems Manager - Secure Setup")
    print("=" * 50)
    
    # Check if .env already exists
    env_file = Path('.env')
    if env_file.exists():
        overwrite = input(".env file already exists. Overwrite? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    # Collect configuration
    print("\n📋 Configuration Setup")
    print("-" * 25)
    
    admin_username = input("Admin Username [daniel]: ").strip() or "daniel"
    admin_password = getpass.getpass("Admin Password: ").strip()
    
    if not admin_password:
        print("❌ Password cannot be empty!")
        return
    
    # Generate secure password hash
    admin_password_hash = hash_password(admin_password)
    
    minicloud_ip = input("MiniCloud IP [192.168.2.2]: ").strip() or "192.168.2.2"
    dashboard_port = input("Dashboard Port [5001]: ").strip() or "5001"
    
    openai_api_key = getpass.getpass("OpenAI API Key (optional): ").strip()
    
    # Generate secure keys
    print("\n🔐 Generating secure keys...")
    secure_keys = generate_secure_keys()
    
    # Create .env file
    env_content = f"""# AI Systems Manager - Environment Configuration
# Generated by setup.py on {os.popen('date').read().strip()}

# Admin Credentials
ADMIN_USERNAME={admin_username}
ADMIN_PASSWORD_HASH={admin_password_hash}

# Network Configuration
MINICLOUD_IP={minicloud_ip}
DASHBOARD_PORT={dashboard_port}
API_PORT=8888

# Security Configuration (AUTO-GENERATED - DO NOT MODIFY)
JWT_SECRET_KEY={secure_keys['JWT_SECRET_KEY']}
SESSION_SECRET_KEY={secure_keys['SESSION_SECRET_KEY']}

# OpenAI Integration
OPENAI_API_KEY={openai_api_key}

# Rate Limiting
MAX_REQUESTS_PER_MINUTE=60
MAX_HEALING_ACTIONS_PER_HOUR=10

# Database Configuration
DATABASE_PATH=./data/meta_agent.db
DATABASE_ENCRYPTION_KEY={secure_keys['DATABASE_ENCRYPTION_KEY']}

# Monitoring Configuration
LOG_LEVEL=INFO
MAX_LOG_SIZE_MB=100
LOG_RETENTION_DAYS=30

# Security Settings
ENABLE_RATE_LIMITING=true
LOG_SECURITY_EVENTS=true
REQUIRE_JWT_AUTH=true

# Docker Configuration
DOCKER_HOST=unix://var/run/docker.sock
"""
    
    # Write .env file
    with open('.env', 'w') as f:
        f.write(env_content)
    
    # Set secure permissions
    os.chmod('.env', 0o600)
    
    print("✅ Configuration complete!")
    print(f"📁 Created .env file with secure settings")
    print(f"🔐 Admin user: {admin_username}")
    print(f"🌐 Dashboard: http://{minicloud_ip}:{dashboard_port}")
    print("\n⚠️  IMPORTANT:")
    print("   - Keep your .env file secure and never commit it to version control")
    print("   - The .env file has been set with restricted permissions (600)")
    print("   - Your password is securely hashed with bcrypt")
    
    if not openai_api_key:
        print("\n⚡ Note: OpenAI API key not provided - AI features will be limited")

if __name__ == "__main__":
    main()